name: Build

on:
  pull_request:
    types: [closed]
    branches:
      - master
    tags:
      - frontend
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install dependencies
        run: yarn
      - name: Install NetlifyCLI
        run: npm install -g netlify-cli@2.59.1
      - name: Deploy in Netlify
        run: yarn workspace @rsn/client deploy:prod
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
